import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/components/index.ts',
    // Componentes individuais
    'src/components/data-display/calendar.tsx',
    'src/components/data-display/carousel.tsx',
    'src/components/data-display/chip.tsx',
    'src/components/data-display/masonry.tsx',
    'src/components/data-display/rating.tsx',
    'src/components/data-display/timeline.tsx',
    'src/components/effects/CelestialBackground.tsx',
    'src/components/effects/FloatingGrid.tsx',
    'src/components/effects/MatrixBackground.tsx',
    'src/components/effects/ParticlesEffect.tsx',
    'src/components/effects/StarsBackground.tsx',
    'src/components/feedback/alert-dialog.tsx',
    'src/components/feedback/alert.tsx',
    'src/components/feedback/badge.tsx',
    'src/components/feedback/empty-state.tsx',
    'src/components/feedback/kpi.tsx',
    'src/components/feedback/notification.tsx',
    'src/components/feedback/progress.tsx',
    'src/components/feedback/skeleton.tsx',
    'src/components/feedback/sonner.tsx',
    'src/components/feedback/spinner.tsx',
    'src/components/forms/checkbox.tsx',
    'src/components/forms/date-picker.tsx',
    'src/components/forms/file-upload.tsx',
    'src/components/forms/form.tsx',
    'src/components/forms/input.tsx',
    'src/components/forms/label.tsx',
    'src/components/forms/phone-input.tsx',
    'src/components/forms/radio-group.tsx',
    'src/components/forms/range-slider.tsx',
    'src/components/forms/search-input.tsx',
    'src/components/forms/select.tsx',
    'src/components/forms/textarea.tsx',
    'src/components/forms/time-picker.tsx',
    'src/components/layout/aspect-ratio.tsx',
    'src/components/layout/breadcrumb.tsx',
    'src/components/layout/card.tsx',
    'src/components/layout/container.tsx',
    'src/components/layout/divider.tsx',
    'src/components/layout/flex.tsx',
    'src/components/layout/grid.tsx',
    'src/components/layout/panel.tsx',
    'src/components/layout/scroll-area.tsx',
    'src/components/layout/separator.tsx',
    'src/components/layout/sheet.tsx',
    'src/components/layout/spacer.tsx',
    'src/components/layout/table.tsx',
    'src/components/navigation/accordion.tsx',
    'src/components/navigation/collapsible.tsx',
    'src/components/navigation/command.tsx',
    'src/components/navigation/menu.tsx',
    'src/components/navigation/navigation-menu.tsx',
    'src/components/navigation/pagination.tsx',
    'src/components/navigation/sidebar.tsx',
    'src/components/navigation/steps.tsx',
    'src/components/navigation/tabs.tsx',
    'src/components/navigation/top-bar.tsx',
    'src/components/overlays/confirm-dialog.tsx',
    'src/components/overlays/context-menu.tsx',
    'src/components/overlays/dialog.tsx',
    'src/components/overlays/drawer.tsx',
    'src/components/overlays/dropdown-menu.tsx',
    'src/components/overlays/hover-card.tsx',
    'src/components/overlays/lightbox.tsx',
    'src/components/overlays/modal.tsx',
    'src/components/overlays/popover.tsx',
    'src/components/overlays/tooltip.tsx',
    'src/components/providers/theme-provider.tsx',
    'src/components/social/action-button.tsx',
    'src/components/social/bookmark-button.tsx',
    'src/components/social/content-card.tsx',
    'src/components/social/like-button.tsx',
    'src/components/social/reading-time.tsx',
    'src/components/social/share-button.tsx',
    'src/components/social/share-menu.tsx',
    'src/components/ui/avatar.tsx',
    'src/components/ui/button.tsx',
    'src/components/ui/fab.tsx',
    'src/components/ui/icon-button.tsx',
    'src/components/ui/link-button.tsx',
    'src/components/ui/segmented-control.tsx',
    'src/components/ui/slider.tsx',
    'src/components/ui/switch.tsx',
    'src/components/ui/toggle.tsx',
    'src/components/utilities/aspect-ratio-box.tsx',
    'src/components/utilities/BackToTop.tsx',
    'src/components/utilities/center.tsx',
    'src/components/utilities/code.tsx',
    'src/components/utilities/CookieBanner.tsx',
    'src/components/utilities/ErrorBoundary.tsx',
    'src/components/utilities/InstallPrompt.tsx',
    'src/components/utilities/kbd.tsx',
    'src/components/utilities/LoadingScreen.tsx',
    'src/components/utilities/PageHeader.tsx',
    'src/components/utilities/quote.tsx',
    'src/components/utilities/ThemeToggle.tsx',
    'src/components/utilities/TokensDemo.tsx',
    'src/components/utilities/UpdateNotification.tsx',
    'src/components/utilities/VisuallyHidden.tsx',
    // Hooks
    'src/hooks/use-carousel-keyboard.ts',
    'src/hooks/use-mobile.ts',
    'src/hooks/use-pwa.ts',
    'src/hooks/use-smooth-scroll.ts',
    'src/hooks/use-table-of-contents.ts',
    'src/hooks/use-theme.ts',
  ],
  format: ['esm', 'cjs'],
  dts: false, // Temporariamente desabilitado
  sourcemap: true,
  clean: true,
  minify: false,
  splitting: false, // Desabilitado para exports individuais
  bundle: false, // Desabilitado para exports individuais
  external: [
    'react', 
    'react-dom',
    'next-themes',
    'next/link',
    'react-loading-indicators',
    '@rainersoft/design-tokens',
    '@radix-ui/react-avatar',
    '@radix-ui/react-separator',
    '@radix-ui/react-progress',
    'class-variance-authority',
    'lucide-react',
    'next',
    'framer-motion',
    'date-fns',
    'react-day-picker',
    'qrcode.react',
    'sonner',
    'cmdk',
    'embla-carousel-react',
    'react-hook-form'
  ],
  target: 'es2020',
  outDir: 'dist',
  esbuildOptions(options) {
    options.banner = {
      js: '"use client"',
    };
  },
});